package com.easycode.templatemgr.model;

import java.util.Date;


/**
 * CodegenMudls generated by MyEclipse Persistence Tools
 */

public class CodegenMudls implements java.io.Serializable
{

	// Fields

    private boolean local;
    
	private String id;
	
	private String seedId;
	
	private String bookmark;
	
	private String mudlCtxt;
	
	private String keyword;
	
    private String beginDate;
    
    private String endDate;
    private String version;
	
	private String createdDate;
	private Date lastUpdatedDate;
	private String enabledFlag;
	
	private String referId;
	
	private String paramDesc;

	private String codeType;
	
	private String mudlAnno = null;
	// Constructors

	public String getMudlAnno()
	{
		return mudlAnno;
	}

	public void setMudlAnno(String mudlAnno)
	{
		this.mudlAnno = mudlAnno;
	}

	public String getBeginDate()
	{
		return beginDate;
	}

	public void setBeginDate(String beginDate)
	{
		this.beginDate = beginDate;
	}

	public String getEndDate()
	{
		return endDate;
	}

	public void setEndDate(String endDate)
	{
		this.endDate = endDate;
	}



	/** default constructor */
	public CodegenMudls()
		{
		}


	// Property accessors

	public String getId()
	{
		return this.id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public String getSeedId()
	{
		return this.seedId;
	}

	public void setSeedId(String seedId)
	{
		this.seedId = seedId;
	}

	public String getMudlCtxt()
	{
		return this.mudlCtxt;
	}

	public void setMudlCtxt(String mudlCtxt)
	{
		this.mudlCtxt = mudlCtxt;
	}


	public String getEnabledFlag()
	{
		return this.enabledFlag;
	}

	public void setEnabledFlag(String enabledFlag)
	{
		this.enabledFlag = enabledFlag;
	}

	public String getBookmark()
	{
		return bookmark;
	}

	public void setBookmark(String bookmark)
	{
		this.bookmark = bookmark;
	}

	public String getKeyword()
	{
		return keyword;
	}

	public void setKeyword(String keyword)
	{
		this.keyword = keyword;
	}

	public String getParamDesc()
	{
		return paramDesc;
	}

	public void setParamDesc(String paramDesc)
	{
		this.paramDesc = paramDesc;
	}

	public String getReferId()
	{
		return referId;
	}

	public void setReferId(String referId)
	{
		this.referId = referId;
	}

	public String getCodeType()
	{
		return codeType;
	}

	public void setCodeType(String codeType)
	{
		this.codeType = codeType;
	}

	public Date getLastUpdatedDate()
	{
		return lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate)
	{
		this.lastUpdatedDate = lastUpdatedDate;
	}

	public String getCreatedDate()
	{
		return createdDate;
	}

	public void setCreatedDate(String createdDate)
	{
		this.createdDate = createdDate;
	}

	public boolean isLocal()
	{
		return local;
	}

	public void setLocal(boolean local)
	{
		this.local = local;
	}

	public String getVersion()
	{
		return version;
	}

	public void setVersion(String version)
	{
		this.version = version;
	}


}